# Site settings
title: Have Eubene to Vancouver?
email: eubene.sa@gmail.com
description: "Eubene Sa is a web developer currently based in Vancouver, BC Canada. He enjoys going to music shows and writes about them. Built using Jekyll and Skeleton."
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://eubene.me" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
