# Site settings
title: Have Eubene to Vancouver?
email: eubene.sa@gmail.com
description: >
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://eubene.me" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
